# This environment.yml file is from the binder icon link on
# the dynamic ipyleaflet page at: http://jupyter.org/widgets
# with the single addition of pydap (bottom).
# It is much smaller than what you get by installing ipyleaflet
# in a new conda environment and then exporting that environment.
name: ipyleaflet
channels:
  - conda-forge
dependencies:
  - ipyleaflet =0.9.0
  - scipy
  - rasterio
  - tqdm
  - requests
  - pillow
  - matplotlib
  - pip:
    - pydap==3.2.2