# This environment.yml file is from the binder icon link on
# the dynamic ipyleaflet page at: http://jupyter.org/widgets
# with the addition of nltk and pip-installed packages.
# It is much smaller than what you get by installing ipyleaflet
# in a new conda environment and then exporting that environment.
name: myjupyter
channels:
  - conda-forge
  - plotly
dependencies:
  - ipyleaflet =0.9.0
  - matplotlib
  - nltk
  - pillow
  - plotly
  - rasterio
  - requests
  - scipy
  - tqdm
  - pip:
    - autocorrect
    - lxml
    - pydap
#   - beautifulsoup4
#   - cfunits
#   - gensim
#   - indra  # causing problems for Binder